server:
  port: 8892
spring:
  application:
    name: client-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8890/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'