spring:
  application:
    name: eureka-server
  security:
    user:
      name: user
      password: 123456
server:
  port: 8890
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

    serviceUrl:
      defaultZone: http://user:123456@localhost:8890/eureka/
  server:
    renewalPercentThreshold: 0.49
